# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictionmarket/crypto/v1/keys.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'predictionmarket/crypto/v1/keys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%predictionmarket/crypto/v1/keys.proto\x12\'predictionmarket.crypto.v1.ethsecp256k1\"\x15\n\x06PubKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x16\n\x07PrivKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x42\x42Z@github.com/Org-43-57/predchaind/crypto/ethsecp256k1;ethsecp256k1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictionmarket.crypto.v1.keys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/Org-43-57/predchaind/crypto/ethsecp256k1;ethsecp256k1'
  _globals['_PUBKEY']._serialized_start=82
  _globals['_PUBKEY']._serialized_end=103
  _globals['_PRIVKEY']._serialized_start=105
  _globals['_PRIVKEY']._serialized_end=127
# @@protoc_insertion_point(module_scope)
