# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictionmarket/poa/v1/tx.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'predictionmarket/poa/v1/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n predictionmarket/poa/v1/tx.proto\x12\x17predictionmarket.poa.v1\x1a\x17\x63osmos/msg/v1/msg.proto\"q\n\rValidatorSlot\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x11\x63onsensus_address\x18\x03 \x01(\t\x12\x19\n\x11\x63onsensus_pub_key\x18\x04 \x01(\x0c\x12\r\n\x05power\x18\x05 \x01(\x03\"s\n\x12MsgSetValidatorSet\x12\x11\n\tauthority\x18\x01 \x01(\t\x12:\n\nvalidators\x18\x02 \x03(\x0b\x32&.predictionmarket.poa.v1.ValidatorSlot:\x0e\x82\xe7\xb0*\tauthority\"\x1c\n\x1aMsgSetValidatorSetResponse\"F\n\x0eMsgUpdateAdmin\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x11\n\tnew_admin\x18\x02 \x01(\t:\x0e\x82\xe7\xb0*\tauthority\"\x18\n\x16MsgUpdateAdminResponse2\xe3\x01\n\x03Msg\x12s\n\x0fSetValidatorSet\x12+.predictionmarket.poa.v1.MsgSetValidatorSet\x1a\x33.predictionmarket.poa.v1.MsgSetValidatorSetResponse\x12g\n\x0bUpdateAdmin\x12\'.predictionmarket.poa.v1.MsgUpdateAdmin\x1a/.predictionmarket.poa.v1.MsgUpdateAdminResponseBEZCgithub.com/Org-43-57/predchaind/proto/predictionmarket/poa/v1;poav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictionmarket.poa.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/Org-43-57/predchaind/proto/predictionmarket/poa/v1;poav1'
  _globals['_MSGSETVALIDATORSET']._loaded_options = None
  _globals['_MSGSETVALIDATORSET']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGUPDATEADMIN']._loaded_options = None
  _globals['_MSGUPDATEADMIN']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_VALIDATORSLOT']._serialized_start=86
  _globals['_VALIDATORSLOT']._serialized_end=199
  _globals['_MSGSETVALIDATORSET']._serialized_start=201
  _globals['_MSGSETVALIDATORSET']._serialized_end=316
  _globals['_MSGSETVALIDATORSETRESPONSE']._serialized_start=318
  _globals['_MSGSETVALIDATORSETRESPONSE']._serialized_end=346
  _globals['_MSGUPDATEADMIN']._serialized_start=348
  _globals['_MSGUPDATEADMIN']._serialized_end=418
  _globals['_MSGUPDATEADMINRESPONSE']._serialized_start=420
  _globals['_MSGUPDATEADMINRESPONSE']._serialized_end=444
  _globals['_MSG']._serialized_start=447
  _globals['_MSG']._serialized_end=674
# @@protoc_insertion_point(module_scope)
