# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictionmarket/testnetmint/v1/tx.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'predictionmarket/testnetmint/v1/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(predictionmarket/testnetmint/v1/tx.proto\x12\x1fpredictionmarket.testnetmint.v1\x1a\x17\x63osmos/msg/v1/msg.proto\"Q\n\x10MsgAdminMintUSDC\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t:\x0e\x82\xe7\xb0*\tauthority\"\x1a\n\x18MsgAdminMintUSDCResponse\"S\n\x10MsgAdminBurnUSDC\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\t:\x0e\x82\xe7\xb0*\tauthority\"\x1a\n\x18MsgAdminBurnUSDCResponse\"F\n\x0eMsgUpdateAdmin\x12\x11\n\tauthority\x18\x01 \x01(\t\x12\x11\n\tnew_admin\x18\x02 \x01(\t:\x0e\x82\xe7\xb0*\tauthority\"\x18\n\x16MsgUpdateAdminResponse2\xfc\x02\n\x03Msg\x12}\n\rAdminMintUSDC\x12\x31.predictionmarket.testnetmint.v1.MsgAdminMintUSDC\x1a\x39.predictionmarket.testnetmint.v1.MsgAdminMintUSDCResponse\x12}\n\rAdminBurnUSDC\x12\x31.predictionmarket.testnetmint.v1.MsgAdminBurnUSDC\x1a\x39.predictionmarket.testnetmint.v1.MsgAdminBurnUSDCResponse\x12w\n\x0bUpdateAdmin\x12/.predictionmarket.testnetmint.v1.MsgUpdateAdmin\x1a\x37.predictionmarket.testnetmint.v1.MsgUpdateAdminResponseBUZSgithub.com/Org-43-57/predchaind/proto/predictionmarket/testnetmint/v1;testnetmintv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictionmarket.testnetmint.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/Org-43-57/predchaind/proto/predictionmarket/testnetmint/v1;testnetmintv1'
  _globals['_MSGADMINMINTUSDC']._loaded_options = None
  _globals['_MSGADMINMINTUSDC']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGADMINBURNUSDC']._loaded_options = None
  _globals['_MSGADMINBURNUSDC']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGUPDATEADMIN']._loaded_options = None
  _globals['_MSGUPDATEADMIN']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGADMINMINTUSDC']._serialized_start=102
  _globals['_MSGADMINMINTUSDC']._serialized_end=183
  _globals['_MSGADMINMINTUSDCRESPONSE']._serialized_start=185
  _globals['_MSGADMINMINTUSDCRESPONSE']._serialized_end=211
  _globals['_MSGADMINBURNUSDC']._serialized_start=213
  _globals['_MSGADMINBURNUSDC']._serialized_end=296
  _globals['_MSGADMINBURNUSDCRESPONSE']._serialized_start=298
  _globals['_MSGADMINBURNUSDCRESPONSE']._serialized_end=324
  _globals['_MSGUPDATEADMIN']._serialized_start=326
  _globals['_MSGUPDATEADMIN']._serialized_end=396
  _globals['_MSGUPDATEADMINRESPONSE']._serialized_start=398
  _globals['_MSGUPDATEADMINRESPONSE']._serialized_end=422
  _globals['_MSG']._serialized_start=425
  _globals['_MSG']._serialized_end=805
# @@protoc_insertion_point(module_scope)
